"""Removed vacany_id field from answers table

Revision ID: af78093edd8b
Revises: ec8a43014a34
Create Date: 2025-11-08 11:53:47.180810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af78093edd8b'
down_revision: Union[str, Sequence[str], None] = 'ec8a43014a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_vacancy')
    op.drop_constraint(op.f('answers_vacancy_id_fkey'), 'answers', type_='foreignkey')
    op.drop_column('answers', 'vacancy_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('answers_vacancy_id_fkey'), 'answers', 'vacancies', ['vacancy_id'], ['id'])
    op.create_table('question_vacancy',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vacancy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('question_vacancy_question_id_fkey')),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], name=op.f('question_vacancy_vacancy_id_fkey')),
    sa.PrimaryKeyConstraint('question_id', 'vacancy_id', name=op.f('question_vacancy_pkey'))
    )
    # ### end Alembic commands ###
