"""Added Cascade

Revision ID: c6094deafa56
Revises: b50b9a87a607
Create Date: 2025-11-22 11:05:50.058975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6094deafa56'
down_revision: Union[str, Sequence[str], None] = 'b50b9a87a607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('answers_question_id_fkey'), 'answers', type_='foreignkey')
    op.drop_constraint(op.f('answers_user_id_fkey'), 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['chat_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questions_vacancy_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_vacancy', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('user_vacancy_user_id_fkey'), 'user_vacancy', type_='foreignkey')
    op.drop_constraint(op.f('user_vacancy_vacancy_id_fkey'), 'user_vacancy', type_='foreignkey')
    op.create_foreign_key(None, 'user_vacancy', 'users', ['user_id'], ['chat_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_vacancy', 'vacancies', ['vacancy_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_vacancy', type_='foreignkey')
    op.drop_constraint(None, 'user_vacancy', type_='foreignkey')
    op.create_foreign_key(op.f('user_vacancy_vacancy_id_fkey'), 'user_vacancy', 'vacancies', ['vacancy_id'], ['id'])
    op.create_foreign_key(op.f('user_vacancy_user_id_fkey'), 'user_vacancy', 'users', ['user_id'], ['chat_id'])
    op.alter_column('user_vacancy', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_vacancy_id_fkey'), 'questions', 'vacancies', ['vacancy_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key(op.f('answers_user_id_fkey'), 'answers', 'users', ['user_id'], ['chat_id'])
    op.create_foreign_key(op.f('answers_question_id_fkey'), 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
